"use client";

import { useState } from "react";

export interface GalleryProject {
  id: number;
  title: string;
  category: string;
  image: string;
  description: string;
  location?: string;
  year?: string;
  slug?: string;
}

export function useGalleryData() {
  const projects: GalleryProject[] = [
    {
      id: 1,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 2.png",
      description: "Desain rumah modern dengan konsep minimalis yang elegan",
      location: "Jakarta Selatan",
      year: "2024",
      slug: "rumah-modern-minimalis",
    },
    {
      id: 2,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 2.png",
      description: "Desain rumah tropis dengan konsep terbuka dan asri",
      location: "Bandung",
      year: "2024",
      slug: "rumah-tropis",
    },
    {
      id: 3,
      title: "Renovasi",
      category: "Renovasi",
      image: "/proses pembangunan/Renovasi Rumah Surabaya.png",
      description: "Renovasi rumah dengan sentuhan modern",
      location: "Surabaya",
      year: "2023",
      slug: "renovasi-rumah",
    },
    {
      id: 4,
      title: "Konstruksi",
      category: "Kontraktor",
      image: "/proses pembangunan/Pembangunan Rumah Surabaya.png",
      description: "Konstruksi rumah baru dengan standar kualitas tinggi",
      location: "Surabaya",
      year: "2024",
      slug: "kontruksi-rumah",
    },
    {
      id: 5,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 2.png",
      description: "Desain rumah dengan gaya industrial yang unik dan modern",
      location: "Depok",
      year: "2023",
      slug: "rumah-industrial",
    },
    {
      id: 6,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 1.png",
      description:
        "Desain rumah dengan konsep Skandinavia yang hangat dan fungsional",
      location: "Jakarta Pusat",
      year: "2024",
      slug: "rumah-skandinavia",
    },
    {
      id: 7,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 1.png",
      description: "Renovasi kantor dengan desain modern dan efisien",
      location: "Jakarta Barat",
      year: "2023",
      slug: "renovasi-kantor",
    },
    {
      id: 8,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 3.png",
      description: "Konstruksi ruko dengan desain komersial yang menarik",
      location: "Jakarta Timur",
      year: "2024",
      slug: "konstruksi-ruko",
    },
    {
      id: 9,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 4.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Tangerang",
      year: "2023",
      slug: "rumah-kontemporer",
    },
    {
      id: 10,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 5.png",
      description: "Desain rumah klasik dengan sentuhan elegan dan mewah",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-klasik",
    },
    {
      id: 11,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 6.png",
      description: "Renovasi toko dengan desain yang menarik dan fungsional",
      location: "Bandung",
      year: "2023",
      slug: "renovasi-toko",
    },
    {
      id: 12,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 7.png",
      description: "Konstruksi gudang dengan desain industri yang efisien",
      location: "Bekasi",
      year: "2024",
      slug: "konstruksi-gudang",
    },
    {
      id: 13,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 8.png",
      description:
        "Desain rumah minimalis dengan sentuhan kekinian dan fungsional",
      location: "Semarang",
      year: "2023",
      slug: "rumah-minimalis",
    },
    {
      id: 14,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 9.png",
      description:
        "Renovasi apartemen dengan desain yang menarik dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-apartemen",
    },
    {
      id: 15,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 10.png",
      description: "Konstruksi villa dengan desain mewah dan nyaman",
      location: "Bali",
      year: "2023",
      slug: "konstruksi-villa",
    },
    {
      id: 16,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 11.png",
      description: "Desain rumah bohemian dengan gaya eklektik dan artistik",
      location: "Malang",
      year: "2024",
      slug: "rumah-bohemian",
    },
    {
      id: 17,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 12.png",
      description: "Renovasi sekolah dengan desain yang modern dan fungsional",
      location: "Yogyakarta",
      year: "2023",
      slug: "renovasi-sekolah",
    },
    {
      id: 18,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 13.png",
      description: "Konstruksi hotel dengan desain mewah dan nyaman",
      location: "Lombok",
      year: "2024",
      slug: "konstruksi-hotel",
    },
    {
      id: 19,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 14.png",
      description:
        "Desain rumah etnik dengan sentuhan budaya lokal yang kental",
      location: "Solo",
      year: "2023",
      slug: "rumah-etnik",
    },
    {
      id: 20,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 15.png",
      description:
        "Renovasi restoran dengan desain yang menarik dan fungsional",
      location: "Medan",
      year: "2024",
      slug: "renovasi-restoran",
    },
    {
      id: 21,
      title: "Rumah Modern",
      category: "Design",
      image: "/desain rumah/rumah modern 16.png",
      description:
        "Konstruksi rumah kost dengan desain yang nyaman dan fungsional",
      location: "Jakarta",
      year: "2023",
      slug: "konstruksi-rumah-kost",
    },
    {
      id: 22,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 2.png",
      description: "Desain rumah futuristik dengan konsep inovatif dan modern",
      location: "Tangerang",
      year: "2024",
      slug: "rumah-futuristik",
    },
    {
      id: 23,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 3.png",
      description:
        "Renovasi pusat perbelanjaan dengan desain yang menarik dan fungsional",
      location: "Bekasi",
      year: "2023",
      slug: "renovasi-pusat-perbelanjaan",
    },
    {
      id: 24,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 4.png",
      description:
        "Konstruksi gedung perkantoran dengan desain modern dan efisien",
      location: "Jakarta Selatan",
      year: "2024",
      slug: "konstruksi-gedung-perkantoran",
    },
    {
      id: 25,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 5.png",
      description:
        "Desain rumah minimalis dengan gaya sederhana dan fungsional",
      location: "Bandung",
      year: "2023",
      slug: "rumah-minimalis",
    },
    {
      id: 26,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 6.png",
      description: "Renovasi klinik dengan desain yang modern dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-klinik",
    },
    {
      id: 27,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 7.png",
      description: "Konstruksi pabrik dengan desain industri yang efisien",
      location: "Cikarang",
      year: "2023",
      slug: "konstruksi-pabrik",
    },
    {
      id: 28,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 8.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
    {
      id: 29,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 9.png",
      description: "Renovasi hotel dengan desain yang menarik dan fungsional",
      location: "Bali",
      year: "2023",
      slug: "renovasi-hotel",
    },
    {
      id: 30,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 10.png",
      description: "Konstruksi restoran dengan desain komersial yang menarik",
      location: "Jakarta Utara",
      year: "2024",
      slug: "konstruksi-restoran",
    },
    {
      id: 31,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 11.png",
      description: "Desain rumah art deco dengan gaya vintage yang elegan",
      location: "Semarang",
      year: "2023",
      slug: "rumah-art-deco",
    },
    {
      id: 32,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 12.png",
      description:
        "Renovasi galeri seni dengan desain yang modern dan fungsional",
      location: "Malang",
      year: "2024",
      slug: "renovasi-galeri-seni",
    },
    {
      id: 33,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 13.png",
      description:
        "Konstruksi perpustakaan dengan desain yang nyaman dan fungsional",
      location: "Solo",
      year: "2023",
      slug: "konstruksi-perpustakaan",
    },
    {
      id: 34,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 14.png",
      description: "Desain rumah mediterania dengan sentuhan hangat dan elegan",
      location: "Padang",
      year: "2024",
      slug: "rumah-mediterania",
    },
    {
      id: 35,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 15.png",
      description: "Renovasi gym dengan desain yang modern dan fungsional",
      location: "Jakarta Pusat",
      year: "2023",
      slug: "renovasi-gym",
    },
    {
      id: 36,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 16.png",
      description:
        "Konstruksi salon kecantikan dengan desain yang menarik dan fungsional",
      location: "Depok",
      year: "2024",
      slug: "konstruksi-salon-kecantikan",
    },
    {
      id: 37,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 17.png",
      description: "Desain rumah minimalis dengan fungsionalitas tinggi",
      location: "Bandung",
      year: "2023",
      slug: "rumah-minimalis",
    },
    {
      id: 38,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 18.png",
      description: "Renovasi klinik dengan desain yang modern dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-klinik",
    },
    {
      id: 39,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 19.png",
      description: "Konstruksi pabrik dengan desain industri yang efisien",
      location: "Cikarang",
      year: "2023",
      slug: "konstruksi-pabrik",
    },
    {
      id: 40,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 20.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
    {
      id: 41,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 21.png",
      description: "Renovasi hotel dengan desain yang menarik dan fungsional",
      location: "Bali",
      year: "2023",
      slug: "renovasi-hotel",
    },
    {
      id: 42,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 22.png",
      description: "Konstruksi restoran dengan desain komersial yang menarik",
      location: "Jakarta Utara",
      year: "2024",
      slug: "konstruksi-restoran",
    },
    {
      id: 43,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 23.png",
      description: "Desain rumah art deco dengan gaya vintage yang elegan",
      location: "Semarang",
      year: "2023",
      slug: "rumah-art-deco",
    },
    {
      id: 44,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 24.png",
      description:
        "Renovasi galeri seni dengan desain yang modern dan fungsional",
      location: "Malang",
      year: "2024",
      slug: "renovasi-galeri-seni",
    },
    {
      id: 45,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 25.png",
      description:
        "Konstruksi perpustakaan dengan desain yang nyaman dan fungsional",
      location: "Solo",
      year: "2023",
      slug: "konstruksi-perpustakaan",
    },
    {
      id: 46,
      title: "Rumah Industrial",
      category: "Design",
      image: "/desain rumah/rumah industrial 26.png",
      description: "Desain rumah mediterania dengan sentuhan hangat dan elegan",
      location: "Padang",
      year: "2024",
      slug: "rumah-mediterania",
    },
    {
      id: 47,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 1.png",
      description: "Renovasi gym dengan desain yang modern dan fungsional",
      location: "Jakarta Pusat",
      year: "2023",
      slug: "renovasi-gym",
    },
    {
      id: 48,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 3.png",
      description:
        "Konstruksi salon kecantikan dengan desain yang menarik dan fungsional",
      location: "Depok",
      year: "2024",
      slug: "konstruksi-salon-kecantikan",
    },
    {
      id: 49,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 4.png",
      description: "Desain rumah bohemian dengan gaya eklektik dan artistik",
      location: "Malang",
      year: "2024",
      slug: "rumah-bohemian",
    },
    {
      id: 50,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 5.png",
      description: "Renovasi sekolah dengan desain yang modern dan fungsional",
      location: "Yogyakarta",
      year: "2023",
      slug: "renovasi-sekolah",
    },
    {
      id: 51,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 6.png",
      description: "Konstruksi hotel dengan desain mewah dan nyaman",
      location: "Lombok",
      year: "2024",
      slug: "konstruksi-hotel",
    },
    {
      id: 52,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 7.png",
      description:
        "Desain rumah etnik dengan sentuhan budaya lokal yang kental",
      location: "Solo",
      year: "2023",
      slug: "rumah-etnik",
    },
    {
      id: 53,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 8.png",
      description:
        "Renovasi restoran dengan desain yang menarik dan fungsional",
      location: "Medan",
      year: "2024",
      slug: "renovasi-restoran",
    },
    {
      id: 54,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 9.png",
      description:
        "Konstruksi rumah kost dengan desain yang nyaman dan fungsional",
      location: "Jakarta",
      year: "2023",
      slug: "konstruksi-rumah-kost",
    },
    {
      id: 55,
      title: "Rumah Skandinavia",
      category: "Design",
      image: "/desain rumah/rumah skandinavia 10.png",
      description: "Desain rumah futuristik dengan konsep inovatif dan modern",
      location: "Tangerang",
      year: "2024",
      slug: "rumah-futuristik",
    },
    {
      id: 56,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 1.png",
      description:
        "Renovasi pusat perbelanjaan dengan desain yang menarik dan fungsional",
      location: "Bekasi",
      year: "2023",
      slug: "renovasi-pusat-perbelanjaan",
    },
    {
      id: 57,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 3.png",
      description:
        "Konstruksi gedung perkantoran dengan desain modern dan efisien",
      location: "Jakarta Selatan",
      year: "2024",
      slug: "konstruksi-gedung-perkantoran",
    },
    {
      id: 58,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 2.png",
      description: "Desain rumah tropis dengan konsep terbuka dan asri",
      location: "Bandung",
      year: "2024",
      slug: "rumah-tropis",
    },
    {
      id: 59,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 4.png",
      description: "Desain rumah modern dengan konsep minimalis yang elegan",
      location: "Jakarta Selatan",
      year: "2024",
      slug: "rumah-modern-minimalis",
    },
    {
      id: 60,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 5.png",
      description: "Renovasi rumah dengan sentuhan modern",
      location: "Surabaya",
      year: "2023",
      slug: "renovasi-rumah",
    },
    {
      id: 61,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 6.png",
      description: "Konstruksi rumah dengan desain minimalis dan nyaman",
      location: "Jakarta",
      year: "2023",
      slug: "konstruksi-rumah",
    },
    {
      id: 62,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 7.png",
      description: "Desain rumah minimalis dengan konsep sederhana dan nyaman",
      location: "Bandung",
      year: "2024",
      slug: "rumah-minimalis",
    },
    {
      id: 63,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 8.png",
      description:
        "Renovasi apartemen dengan desain yang menarik dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-apartemen",
    },
    {
      id: 64,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 9.png",
      description: "Konstruksi villa dengan desain mewah dan nyaman",
      location: "Bali",
      year: "2023",
      slug: "konstruksi-villa",
    },
    {
      id: 65,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 10.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
    {
      id: 66,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 11.png",
      description: "Desain rumah klasik dengan sentuhan elegan dan mewah",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-klasik",
    },
    {
      id: 67,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 12.png",
      description: "Renovasi toko dengan desain yang menarik dan fungsional",
      location: "Bandung",
      year: "2023",
      slug: "renovasi-toko",
    },
    {
      id: 68,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 13.png",
      description: "Konstruksi gudang dengan desain industri yang efisien",
      location: "Bekasi",
      year: "2023",
      slug: "konstruksi-gudang",
    },
    {
      id: 69,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 14.png",
      description: "Desain rumah bohemian dengan gaya eklektik dan artistik",
      location: "Malang",
      year: "2024",
      slug: "rumah-bohemian",
    },
    {
      id: 70,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 15.png",
      description: "Renovasi sekolah dengan desain yang modern dan fungsional",
      location: "Yogyakarta",
      year: "2023",
      slug: "renovasi-sekolah",
    },
    {
      id: 71,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 16.png",
      description: "Konstruksi hotel dengan desain mewah dan nyaman",
      location: "Lombok",
      year: "2024",
      slug: "konstruksi-hotel",
    },
    {
      id: 72,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 17.png",
      description:
        "Desain rumah etnik dengan sentuhan budaya lokal yang kental",
      location: "Solo",
      year: "2023",
      slug: "rumah-etnik",
    },
    {
      id: 73,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 18.png",
      description:
        "Renovasi restoran dengan desain yang menarik dan fungsional",
      location: "Medan",
      year: "2024",
      slug: "renovasi-restoran",
    },
    {
      id: 74,
      title: "Rumah Tropis",
      category: "Design",
      image: "/desain rumah/rumah tropis 19.png",
      description:
        "Konstruksi rumah kost dengan desain yang nyaman dan fungsional",
      location: "Jakarta",
      year: "2023",
      slug: "konstruksi-rumah-kost",
    },
    {
      id: 75,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 1.png",
      description: "Desain rumah futuristik dengan konsep inovatif dan modern",
      location: "Tangerang",
      year: "2024",
      slug: "rumah-futuristik",
    },
    {
      id: 76,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 2.png",
      description:
        "Renovasi pusat perbelanjaan dengan desain yang menarik dan fungsional",
      location: "Bekasi",
      year: "2023",
      slug: "renovasi-pusat-perbelanjaan",
    },
    {
      id: 77,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 3.png",
      description:
        "Konstruksi gedung perkantoran dengan desain modern dan efisien",
      location: "Jakarta Selatan",
      year: "2024",
      slug: "konstruksi-gedung-perkantoran",
    },
    {
      id: 78,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 4.png",
      description: "Desain rumah minimalis dengan konsep sederhana dan nyaman",
      location: "Bandung",
      year: "2024",
      slug: "rumah-minimalis",
    },
    {
      id: 79,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 5.png",
      description:
        "Renovasi apartemen dengan desain yang menarik dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-apartemen",
    },
    {
      id: 80,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 6.png",
      description: "Konstruksi villa dengan desain mewah dan nyaman",
      location: "Bali",
      year: "2023",
      slug: "konstruksi-villa",
    },
    {
      id: 81,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 7.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
    {
      id: 82,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 8.png",
      description: "Desain rumah klasik dengan sentuhan elegan dan mewah",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-klasik",
    },
    {
      id: 83,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 9.png",
      description: "Renovasi toko dengan desain yang menarik dan fungsional",
      location: "Bandung",
      year: "2023",
      slug: "renovasi-toko",
    },
    {
      id: 84,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 10.png",
      description: "Konstruksi gudang dengan desain industri yang efisien",
      location: "Bekasi",
      year: "2024",
      slug: "konstruksi-gudang",
    },
    {
      id: 85,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 11.png",
      description: "Desain rumah bohemian dengan gaya eklektik dan artistik",
      location: "Malang",
      year: "2024",
      slug: "rumah-bohemian",
    },
    {
      id: 86,
      title: "Rumah Minimalis",
      category: "Design",
      image: "/desain rumah/rumah minimalis 12.png",
      description: "Renovasi sekolah dengan desain yang modern dan fungsional",
      location: "Yogyakarta",
      year: "2023",
      slug: "renovasi-sekolah",
    },
    {
      id: 87,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 1.png",
      description: "Konstruksi hotel dengan desain mewah dan nyaman",
      location: "Lombok",
      year: "2024",
      slug: "konstruksi-hotel",
    },
    {
      id: 88,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 2.png",
      description:
        "Desain rumah etnik dengan sentuhan budaya lokal yang kental",
      location: "Solo",
      year: "2023",
      slug: "rumah-etnik",
    },
    {
      id: 89,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 3.png",
      description:
        "Renovasi restoran dengan desain yang menarik dan fungsional",
      location: "Medan",
      year: "2024",
      slug: "renovasi-restoran",
    },
    {
      id: 90,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 4.png",
      description:
        "Konstruksi rumah kost dengan desain yang nyaman dan fungsional",
      location: "Jakarta",
      year: "2023",
      slug: "konstruksi-rumah-kost",
    },
    {
      id: 91,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 5.png",
      description: "Desain rumah futuristik dengan konsep inovatif dan modern",
      location: "Tangerang",
      year: "2024",
      slug: "rumah-futuristik",
    },
    {
      id: 92,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 6.png",
      description:
        "Renovasi pusat perbelanjaan dengan desain yang menarik dan fungsional",
      location: "Bekasi",
      year: "2023",
      slug: "renovasi-pusat-perbelanjaan",
    },
    {
      id: 93,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 7.png",
      description:
        "Konstruksi gedung perkantoran dengan desain modern dan efisien",
      location: "Malang",
      year: "2024",
      slug: "konstruksi-gedung-perkantoran",
    },
    {
      id: 94,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 8.png",
      description:
        "Desain rumah japandi dengan perpaduan gaya Jepang dan Skandinavia",
      location: "Bandung",
      year: "2024",
      slug: "rumah-japandi",
    },
    {
      id: 95,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 9.png",
      description:
        "Renovasi apartemen dengan desain yang menarik dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-apartemen",
    },
    {
      id: 96,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 10.png",
      description: "Konstruksi villa dengan desain mewah dan nyaman",
      location: "Bali",
      year: "2023",
      slug: "konstruksi-villa",
    },
    {
      id: 97,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 11.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
    {
      id: 98,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 12.png",
      description: "Desain rumah klasik dengan sentuhan elegan dan mewah",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-klasik",
    },
    {
      id: 99,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 13.png",
      description: "Renovasi toko dengan desain yang menarik dan fungsional",
      location: "Bandung",
      year: "2023",
      slug: "renovasi-toko",
    },
    {
      id: 100,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 14.png",
      description: "Konstruksi gudang dengan desain industri yang efisien",
      location: "Bekasi",
      year: "2024",
      slug: "konstruksi-gudang",
    },
    {
      id: 101,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 15.png",
      description:
        "Desain rumah minimalis dengan sentuhan sederhana dan fungsional",
      location: "Malang",
      year: "2024",
      slug: "rumah-minimalis",
    },
    {
      id: 102,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 16.png",
      description:
        "Renovasi apartemen dengan desain yang menarik dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-apartemen",
    },
    {
      id: 103,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 17.png",
      description: "Konstruksi villa dengan desain mewah dan nyaman",
      location: "Bali",
      year: "2023",
      slug: "konstruksi-villa",
    },
    {
      id: 104,
      title: "Rumah Japandi",
      category: "Design",
      image: "/desain rumah/rumah japandi 18.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
    {
      id: 105,
      title: "Renovasi",
      category: "Renovasi",
      image: "/proses pembangunan/renovasi-1.png",
      description: "Desain rumah klasik dengan sentuhan elegan dan mewah",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-klasik",
    },
    {
      id: 106,
      title: "Renovasi",
      category: "Renovasi",
      image: "/proses pembangunan/renovasi-2.png",
      description: "Renovasi toko dengan desain yang menarik dan fungsional",
      location: "Bandung",
      year: "2023",
      slug: "renovasi-toko",
    },
    {
      id: 107,
      title: "Renovasi",
      category: "Renovasi",
      image: "/proses pembangunan/renovasi-3.png",
      description: "Konstruksi gudang dengan desain industri yang efisien",
      location: "Bekasi",
      year: "2024",
      slug: "konstruksi-gudang",
    },
    {
      id: 108,
      title: "Renovasi",
      category: "Renovasi",
      image: "/proses pembangunan/renovasi-4.png",
      description:
        "Desain rumah minimalis dengan sentuhan sederhana dan fungsional",
      location: "Malang",
      year: "2024",
      slug: "rumah-minimalis",
    },
    {
      id: 109,
      title: "Renovasi",
      category: "Renovasi",
      image: "/proses pembangunan/renovasi-5.png",
      description:
        "Renovasi apartemen dengan desain yang menarik dan fungsional",
      location: "Surabaya",
      year: "2024",
      slug: "renovasi-apartemen",
    },
    {
      id: 110,
      title: "Konstruksi",
      category: "Kontraktor",
      image: "/proses pembangunan/kontruksi-1.png",
      description: "Konstruksi villa dengan desain mewah dan nyaman",
      location: "Bali",
      year: "2023",
      slug: "konstruksi-villa",
    },
    {
      id: 111,
      title: "Konstruksi",
      category: "Kontraktor",
      image: "/proses pembangunan/kontruksi-2.png",
      description:
        "Desain rumah kontemporer dengan elemen modern dan fungsional",
      location: "Yogyakarta",
      year: "2024",
      slug: "rumah-kontemporer",
    },
  ];

  return { projects };
}

export function useProjectFilter() {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [currentPage, setCurrentPage] = useState(1);

  const categories = [
    "All",
    "Kontraktor",
    "Design",
    "Renovasi",
    // "Kelola Properti",
  ];

  const filterProjects = (projects: GalleryProject[], itemsPerPage = 9) => {
    const filteredProjects = projects.filter((project) => {
      const matchesSearch =
        project.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        project.description.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory =
        selectedCategory === "All" || project.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });

    const totalPages = Math.ceil(filteredProjects.length / itemsPerPage);
    const startIndex = (currentPage - 1) * itemsPerPage;
    const currentProjects = filteredProjects.slice(
      startIndex,
      startIndex + itemsPerPage
    );

    return {
      filteredProjects,
      currentProjects,
      totalPages,
      currentPage,
    };
  };

  return {
    searchTerm,
    setSearchTerm,
    selectedCategory,
    setSelectedCategory,
    currentPage,
    setCurrentPage,
    categories,
    filterProjects,
  };
}
